package main

import (
	"context"
	"encoding/base64"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/labstack/echo/v4"
)

// ─── Batch Sync API ─────────────────────────────────────────────
// POST /api/inspections/sync — idempotent batch sync endpoint for offline-queued inspections.
// Accepts an array of inspections (with optional inline photos) and processes each one.
// Each inspection must include a client_id (UUID generated by IndexedDB) for idempotency.

// SyncRequest is the top-level batch payload from the offline sync queue.
type SyncRequest struct {
	Inspections []SyncInspection `json:"inspections"`
}

// SyncInspection is a single queued inspection with a client-generated UUID for idempotency.
type SyncInspection struct {
	ClientID      string                    `json:"client_id"`      // UUID from IndexedDB — used for idempotency
	TemplateID    *int                      `json:"template_id,omitempty"`
	PropertyID    int                       `json:"property_id"`
	PropertyName  string                    `json:"property_name"`
	BuildingID    *int                      `json:"building_id,omitempty"`
	UnitID        *int                      `json:"unit_id,omitempty"`
	InspectorID   *string                   `json:"inspector_id,omitempty"`
	InspectorName string                    `json:"inspector_name"`
	Notes         *string                   `json:"notes,omitempty"`
	Responses     []SyncItemResponse        `json:"responses"`
	AdhocItems    []AdhocItemSubmission     `json:"adhoc_items,omitempty"`
	Photos        []SyncPhoto               `json:"photos,omitempty"`
	Complete      bool                      `json:"complete"`
	CreatedAt     *time.Time                `json:"created_at,omitempty"` // original offline timestamp
}

// SyncItemResponse is a checklist item response within a sync payload.
type SyncItemResponse struct {
	ItemID int        `json:"item_id"`
	Status ItemStatus `json:"status"`
	Notes  *string    `json:"notes,omitempty"`
	Photos []SyncPhoto `json:"photos,omitempty"` // inline photos for this specific item
}

// SyncPhoto is a base64-encoded photo included in the sync payload.
type SyncPhoto struct {
	ClientPhotoID string  `json:"client_photo_id,omitempty"` // client-side photo UUID
	ItemID        *int    `json:"item_id,omitempty"`         // template item (nil = general inspection photo)
	AdhocIndex    *int    `json:"adhoc_index,omitempty"`     // index into adhoc_items array (for linking after insert)
	Filename      string  `json:"filename"`
	ContentType   string  `json:"content_type"`
	DataBase64    string  `json:"data_base64"`
	Caption       *string `json:"caption,omitempty"`
	Lat           *float64 `json:"lat,omitempty"`
	Lng           *float64 `json:"lng,omitempty"`
}

// SyncResponse is the batch response returned to the client.
type SyncResponse struct {
	Results []SyncResult `json:"results"`
	Summary SyncSummary  `json:"summary"`
}

// SyncResult is the per-inspection result within a batch sync response.
type SyncResult struct {
	ClientID     string `json:"client_id"`
	Status       string `json:"status"` // "created", "duplicate", "error"
	InspectionID *int   `json:"inspection_id,omitempty"`
	PhotoCount   int    `json:"photo_count"`
	Error        string `json:"error,omitempty"`
}

// SyncSummary provides aggregate counts for the batch.
type SyncSummary struct {
	Total      int `json:"total"`
	Created    int `json:"created"`
	Duplicates int `json:"duplicates"`
	Errors     int `json:"errors"`
}

// ─── Database: Idempotency Key Table ────────────────────────────

// CreateSyncTables creates the idempotency tracking table.
func (db *DB) CreateSyncTables(ctx context.Context) error {
	sql := `
	CREATE TABLE IF NOT EXISTS inspection_sync_keys (
		client_id VARCHAR(200) PRIMARY KEY,
		inspection_id INTEGER NOT NULL REFERENCES inspections(id) ON DELETE CASCADE,
		synced_at TIMESTAMPTZ DEFAULT NOW()
	);
	CREATE INDEX IF NOT EXISTS idx_sync_keys_inspection ON inspection_sync_keys(inspection_id);
	`
	_, err := db.pool.Exec(ctx, sql)
	return err
}

// LookupSyncKey checks if a client_id has already been synced, returning the inspection ID if so.
func (db *DB) LookupSyncKey(ctx context.Context, clientID string) (*int, error) {
	var inspectionID int
	err := db.pool.QueryRow(ctx,
		`SELECT inspection_id FROM inspection_sync_keys WHERE client_id = $1`, clientID,
	).Scan(&inspectionID)
	if err != nil {
		return nil, err // pgx.ErrNoRows if not found
	}
	return &inspectionID, nil
}

// InsertSyncKey records a client_id → inspection_id mapping for idempotency.
func (db *DB) InsertSyncKey(ctx context.Context, clientID string, inspectionID int) error {
	_, err := db.pool.Exec(ctx,
		`INSERT INTO inspection_sync_keys (client_id, inspection_id) VALUES ($1, $2) ON CONFLICT (client_id) DO NOTHING`,
		clientID, inspectionID,
	)
	return err
}

// ─── Batch Sync Handler ─────────────────────────────────────────

// POST /api/inspections/sync — idempotent batch sync for offline-queued inspections + photos.
func (a *App) BatchSyncHandler(c echo.Context) error {
	ctx := c.Request().Context()

	var req SyncRequest
	if err := c.Bind(&req); err != nil {
		log.Printf("batch sync bind error: %v", err)
		return c.JSON(http.StatusBadRequest, map[string]string{
			"error": "Invalid request body: " + err.Error(),
		})
	}

	if len(req.Inspections) == 0 {
		return c.JSON(http.StatusOK, SyncResponse{
			Results: []SyncResult{},
			Summary: SyncSummary{},
		})
	}

	// Cap batch size to prevent abuse
	const maxBatchSize = 50
	if len(req.Inspections) > maxBatchSize {
		return c.JSON(http.StatusBadRequest, map[string]string{
			"error": fmt.Sprintf("batch size %d exceeds maximum of %d", len(req.Inspections), maxBatchSize),
		})
	}

	results := make([]SyncResult, 0, len(req.Inspections))
	var created, duplicates, errors int

	for _, syncInsp := range req.Inspections {
		result := a.processSyncInspection(ctx, syncInsp)
		results = append(results, result)

		switch result.Status {
		case "created":
			created++
		case "duplicate":
			duplicates++
		case "error":
			errors++
		}
	}

	return c.JSON(http.StatusOK, SyncResponse{
		Results: results,
		Summary: SyncSummary{
			Total:      len(req.Inspections),
			Created:    created,
			Duplicates: duplicates,
			Errors:     errors,
		},
	})
}

// processSyncInspection handles a single inspection within the batch.
// Returns a SyncResult indicating created, duplicate, or error.
func (a *App) processSyncInspection(ctx context.Context, syncInsp SyncInspection) SyncResult {
	result := SyncResult{ClientID: syncInsp.ClientID}

	// Validate client_id
	if strings.TrimSpace(syncInsp.ClientID) == "" {
		result.Status = "error"
		result.Error = "client_id is required for idempotent sync"
		return result
	}

	// Validate required fields
	if syncInsp.PropertyName == "" {
		result.Status = "error"
		result.Error = "property_name is required"
		return result
	}
	if syncInsp.InspectorName == "" {
		result.Status = "error"
		result.Error = "inspector_name is required"
		return result
	}

	// Validate response statuses
	for i, resp := range syncInsp.Responses {
		if !ValidItemStatuses[resp.Status] {
			result.Status = "error"
			result.Error = fmt.Sprintf("invalid status %q for responses[%d]", resp.Status, i)
			return result
		}
		if resp.ItemID <= 0 {
			result.Status = "error"
			result.Error = fmt.Sprintf("invalid item_id for responses[%d]", i)
			return result
		}
	}

	// Validate adhoc items
	for i, adhoc := range syncInsp.AdhocItems {
		if strings.TrimSpace(adhoc.Label) == "" {
			result.Status = "error"
			result.Error = fmt.Sprintf("label is required for adhoc_items[%d]", i)
			return result
		}
		if adhoc.Status != nil && !ValidItemStatuses[*adhoc.Status] {
			result.Status = "error"
			result.Error = fmt.Sprintf("invalid status %q for adhoc_items[%d]", *adhoc.Status, i)
			return result
		}
	}

	// ── Idempotency check ──
	existingID, err := a.db.LookupSyncKey(ctx, syncInsp.ClientID)
	if err == nil && existingID != nil {
		// Already synced — return duplicate with the existing inspection ID
		result.Status = "duplicate"
		result.InspectionID = existingID
		log.Printf("sync duplicate: client_id=%s → inspection_id=%d", syncInsp.ClientID, *existingID)
		return result
	}

	// ── Create the inspection via existing SubmitInspection ──
	sub := InspectionSubmission{
		TemplateID:    syncInsp.TemplateID,
		PropertyID:    syncInsp.PropertyID,
		PropertyName:  syncInsp.PropertyName,
		BuildingID:    syncInsp.BuildingID,
		UnitID:        syncInsp.UnitID,
		InspectorID:   syncInsp.InspectorID,
		InspectorName: syncInsp.InspectorName,
		Notes:         syncInsp.Notes,
		AdhocItems:    syncInsp.AdhocItems,
		Complete:      syncInsp.Complete,
	}

	// Convert SyncItemResponse to InspectionItemSubmission (strip inline photos)
	sub.Responses = make([]InspectionItemSubmission, len(syncInsp.Responses))
	for i, r := range syncInsp.Responses {
		sub.Responses[i] = InspectionItemSubmission{
			ItemID: r.ItemID,
			Status: r.Status,
			Notes:  r.Notes,
		}
	}

	insp, err := a.db.SubmitInspection(ctx, sub)
	if err != nil {
		result.Status = "error"
		result.Error = "Failed to save inspection: " + err.Error()
		log.Printf("sync submit error for client_id=%s: %v", syncInsp.ClientID, err)
		return result
	}

	// Record the idempotency key
	if err := a.db.InsertSyncKey(ctx, syncInsp.ClientID, insp.ID); err != nil {
		log.Printf("sync key insert warning for client_id=%s: %v", syncInsp.ClientID, err)
		// Non-fatal — the inspection was created, just the key wasn't recorded
	}

	// ── Process inline photos ──
	photoCount := 0

	// Collect all photos: top-level + per-response inline
	allPhotos := make([]SyncPhoto, 0, len(syncInsp.Photos))
	allPhotos = append(allPhotos, syncInsp.Photos...)
	for _, resp := range syncInsp.Responses {
		for _, p := range resp.Photos {
			// Ensure item_id is set from the response
			if p.ItemID == nil {
				itemID := resp.ItemID
				p.ItemID = &itemID
			}
			allPhotos = append(allPhotos, p)
		}
	}

	// Get adhoc item IDs for linking (they were just created in order)
	var adhocIDs []int
	if len(syncInsp.AdhocItems) > 0 {
		adhocIDs, err = a.db.GetAdhocItemIDs(ctx, insp.ID)
		if err != nil {
			log.Printf("sync: failed to get adhoc item IDs for inspection %d: %v", insp.ID, err)
		}
	}

	for _, photo := range allPhotos {
		err := a.processSyncPhoto(ctx, insp.ID, photo, adhocIDs)
		if err != nil {
			log.Printf("sync photo error for inspection %d: %v", insp.ID, err)
			continue // non-fatal: skip failed photos
		}
		photoCount++
	}

	result.Status = "created"
	result.InspectionID = &insp.ID
	result.PhotoCount = photoCount

	log.Printf("sync created: client_id=%s → inspection_id=%d (%d photos)",
		syncInsp.ClientID, insp.ID, photoCount)
	return result
}

// processSyncPhoto decodes and saves a single base64-encoded photo from the sync payload.
func (a *App) processSyncPhoto(ctx context.Context, inspectionID int, photo SyncPhoto, adhocIDs []int) error {
	if photo.DataBase64 == "" {
		return fmt.Errorf("empty photo data")
	}

	// Decode base64 data
	data, err := base64.StdEncoding.DecodeString(photo.DataBase64)
	if err != nil {
		return fmt.Errorf("decode base64: %w", err)
	}

	if len(data) == 0 {
		return fmt.Errorf("decoded photo data is empty")
	}

	// Determine file extension from content type or filename
	ext := filepath.Ext(photo.Filename)
	if ext == "" {
		switch photo.ContentType {
		case "image/jpeg", "image/jpg":
			ext = ".jpg"
		case "image/png":
			ext = ".png"
		case "image/webp":
			ext = ".webp"
		case "image/heic":
			ext = ".heic"
		default:
			ext = ".jpg"
		}
	}

	// Generate unique filename and storage path
	dateDir := time.Now().Format("2006-01-02")
	fileUUID := uuid.New().String()
	filename := fileUUID + ext
	storagePath := filepath.Join(a.config.StoragePath, "inspections", dateDir, filename)
	thumbPath := filepath.Join(a.config.ThumbPath, "inspections", dateDir, filename)

	// Ensure directories exist
	os.MkdirAll(filepath.Dir(storagePath), 0755)
	os.MkdirAll(filepath.Dir(thumbPath), 0755)

	// Write the raw file
	if err := os.WriteFile(storagePath, data, 0644); err != nil {
		return fmt.Errorf("write photo file: %w", err)
	}

	// Try to generate thumbnail (best-effort — don't fail the sync if thumbnail fails)
	var thumbPathPtr *string
	thumb, err := generateThumbnailFromBytes(data, ext)
	if err == nil && thumb != nil {
		if writeErr := os.WriteFile(thumbPath, thumb, 0644); writeErr == nil {
			thumbPathPtr = &thumbPath
		}
	}

	// Determine item linkage
	var itemID *int
	var adhocItemID *int

	if photo.ItemID != nil && *photo.ItemID > 0 {
		itemID = photo.ItemID
	} else if photo.AdhocIndex != nil && *photo.AdhocIndex >= 0 && *photo.AdhocIndex < len(adhocIDs) {
		aid := adhocIDs[*photo.AdhocIndex]
		adhocItemID = &aid
	}

	// Insert photo record
	p := InspectionPhoto{
		InspectionID: inspectionID,
		ItemID:       itemID,
		AdhocItemID:  adhocItemID,
		Filename:     filename,
		StoragePath:  storagePath,
		ThumbPath:    thumbPathPtr,
		Caption:      photo.Caption,
		Lat:          photo.Lat,
		Lng:          photo.Lng,
		FileSize:     intPtr(len(data)),
	}

	return a.db.InsertInspectionPhoto(ctx, &p)
}

// GetAdhocItemIDs returns the IDs of all adhoc items for an inspection, in sort_order.
func (db *DB) GetAdhocItemIDs(ctx context.Context, inspectionID int) ([]int, error) {
	rows, err := db.pool.Query(ctx,
		`SELECT id FROM inspection_adhoc_items WHERE inspection_id = $1 ORDER BY sort_order, id`,
		inspectionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var ids []int
	for rows.Next() {
		var id int
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, nil
}

// generateThumbnailFromBytes is a simple wrapper that decodes image bytes and creates a thumbnail.
// Returns nil if image processing fails (non-fatal for sync).
func generateThumbnailFromBytes(data []byte, ext string) ([]byte, error) {
	// For sync photos, we skip thumbnail generation here — the full image pipeline
	// can process thumbnails asynchronously or on first access. This keeps sync fast.
	// TODO: integrate with existing imaging.go ProcessUpload for full EXIF/orient/thumb pipeline
	return nil, nil
}

// intPtr returns a pointer to an int value.
func intPtr(v int) *int {
	return &v
}
